#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "==> Mac Defaults"
sh ${DIR}/setup/macos.sh
echo ""

echo "==> Homebrew"
sh ${DIR}/setup/brew.sh
echo ""

echo "==> nvm"
sh ${DIR}/setup/nvm.sh
echo ""

${DIR}/symlink