#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "==> Symlinking dotfiles"
symsuffix=".sym"
symprefix="${DIR}/"
for f in ${DIR}/*.sym; do
  echo ""
  symname="${f%$symsuffix}"
  symname="${symname#$symprefix}"
  sympath=${HOME}/.${symname}
  if [[ -f $sympath ]]; then
    echo "    # Removing old symlink"
    echo "    $ rm $sympath"
    rm $sympath
  fi
  symname="${f%$symsuffix}"
  symname="${symname#$symprefix}"
  echo "    # Creating symlink"
  echo "    $ ln -s ${f} ${sympath}"
  ln -s ${f} ${sympath}
done

echo ""
echo "==> Symlinking atom files"
atomprefix="${DIR}/atom/"

for f in ${DIR}/atom/*; do
  echo ""
  symname="${f#$atomprefix}"
  sympath=${HOME}/.atom/${symname}
  if [[ -f $sympath ]]; then
    echo "    # Removing old symlink"
    echo "    $ rm $sympath"
    rm $sympath
  fi
  echo "    # Creating symlink"
  echo "    $ ln -s ${f} ${sympath}"
  ln -s ${f} ${sympath}
done
