#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "==> Symlinking dotfiles"
suffix=".sym"
prefix="${DIR}/"
for f in ${DIR}/*.sym; do
  echo ""
  symname="${f%$suffix}"
  symname="${symname#$prefix}"
  sympath=${HOME}/.${symname}
  if [[ -f $sympath ]]; then
    echo "    # Removing old symlink"
    echo "    $ rm $sympath"
    rm $sympath
  fi
  symname="${f%$suffix}"
  symname="${symname#$prefix}"
  echo "    # Creating symlink"
  echo "    $ ln -s ${f} ${sympath}"
  ln -s ${f} ${sympath}
done

echo ""
echo "==> Symlinking atom files"
echo ""
if [[ -f ${HOME}/.atom/styles.less ]]; then
  echo "    # Removing old styles.less"
  echo "    $ rm ${HOME}/.atom/styles.less"
  rm ${HOME}/.atom/styles.less
fi
echo "    # Creating symlink"
echo "    $ ln -s ${DIR}/atom/styles.less ${HOME}/.atom/styles.less"
ln -s ${DIR}/atom/styles.less ${HOME}/.atom/styles.less
echo ""

if [[ -f ${HOME}/.atom/init.coffee ]]; then
  echo "    # Removing old init.coffee"
  echo "    $ rm ${HOME}/.atom/init.coffee"
  rm ${HOME}/.atom/init.coffee
fi
echo "    # Creating symlink"
echo "    $ ln -s ${DIR}/atom/init.coffee ${HOME}/.atom/init.coffee"
ln -s ${DIR}/atom/init.coffee ${HOME}/.atom/init.coffee
